clear -f
mkoctfile ("tensorflow.cc", ...
           "OCT_TF_Buffer.cc", ...
           "OCT_TF_DataType.cc", ...
           "OCT_TF_Graph.cc", ...
           "OCT_TF_Status.cc", ...
           "OCT_TF_String.cc", ...
           "OCT_TF_Tensor.cc", ...
##  "-L /home/promitheas/Downloads/libtensorflow-cpu-linux-x86_64-2.15.0/lib", ...
  "-ltensorflow")
